import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import { planAtLeast } from "@/lib/plan-context";
import type { Plan } from "@/lib/plan-context";

// GET — owner fetches their team member list
export async function GET() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: members, error } = await supabase
    .from("team_members")
    .select("id, member_email, member_id, status, role, invited_at, accepted_at")
    .eq("owner_id", user.id)
    .neq("status", "removed")
    .order("invited_at", { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ members: members ?? [] });
}

// POST — owner invites a new member by email
export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Must be Advanced plan
  const { data: profile } = await supabase.from("profiles").select("plan, smtp_email, smtp_password, business_name, full_name").eq("id", user.id).single();
  if (!planAtLeast((profile?.plan || "free") as Plan, "advanced")) {
    return NextResponse.json({ error: "Team invitations require the Advanced plan." }, { status: 403 });
  }

  const { email, role } = await request.json();
  if (!email || typeof email !== "string") {
    return NextResponse.json({ error: "Email is required" }, { status: 400 });
  }
  const memberRole = ["admin", "accountant", "viewer"].includes(role) ? role : "admin";
  const normalizedEmail = email.trim().toLowerCase();
  if (normalizedEmail === user.email?.toLowerCase()) {
    return NextResponse.json({ error: "You cannot invite yourself" }, { status: 400 });
  }

  // Upsert: if already pending, refresh token (regenerated by default); if accepted, re-invite
  const { data: existing } = await supabase
    .from("team_members")
    .select("id, status")
    .eq("owner_id", user.id)
    .eq("member_email", normalizedEmail)
    .maybeSingle();

  if (existing?.status === "accepted") {
    return NextResponse.json({ error: "This person is already an active team member." }, { status: 409 });
  }

  let inviteToken: string;
  if (existing) {
    // Refresh token for re-invite
    const { data: updated, error } = await supabase
      .from("team_members")
      .update({ status: "pending", accepted_at: null, role: memberRole })
      .eq("id", existing.id)
      .select("invite_token")
      .single();
    if (error || !updated) return NextResponse.json({ error: error?.message ?? "Failed to update invite" }, { status: 500 });
    inviteToken = updated.invite_token;
  } else {
    const { data: inserted, error } = await supabase
      .from("team_members")
      .insert({ owner_id: user.id, member_email: normalizedEmail, role: memberRole })
      .select("invite_token")
      .single();
    if (error || !inserted) return NextResponse.json({ error: error?.message ?? "Failed to create invite" }, { status: 500 });
    inviteToken = inserted.invite_token;
  }

  // Send invite email via owner's SMTP if configured
  if (profile?.smtp_email && profile?.smtp_password) {
    try {
      const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
      const inviteUrl = `${appUrl}/invite/${inviteToken}`;
      const senderName = profile.business_name || profile.full_name || "Your workspace owner";
      const nodemailer = await import("nodemailer");
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: { user: profile.smtp_email, pass: profile.smtp_password },
      });
      await transporter.sendMail({
        from: `"${senderName}" <${profile.smtp_email}>`,
        to: normalizedEmail,
        subject: `You've been invited to join ${senderName}'s workspace`,
        html: `<p>Hi,</p><p>${senderName} has invited you to collaborate in their FreelanceFlow workspace.</p><p><a href="${inviteUrl}" style="color:#7c3aed;font-weight:bold">Accept Invitation</a></p><p>— FreelanceFlow</p>`,
      });
    } catch { /* don't fail if email fails */ }
  }

  return NextResponse.json({ ok: true });
}

// PATCH — owner changes a member's role
export async function PATCH(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { memberId, role } = await request.json();
  if (!memberId || !["admin", "accountant", "viewer"].includes(role)) {
    return NextResponse.json({ error: "memberId and a valid role are required" }, { status: 400 });
  }

  const { error } = await supabase
    .from("team_members")
    .update({ role })
    .eq("id", memberId)
    .eq("owner_id", user.id);

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true });
}

// DELETE — owner removes a team member
export async function DELETE(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { memberId } = await request.json();
  if (!memberId) return NextResponse.json({ error: "memberId required" }, { status: 400 });

  const { error } = await supabase
    .from("team_members")
    .update({ status: "removed" })
    .eq("id", memberId)
    .eq("owner_id", user.id);

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true });
}
